export const categoryData = [
  {
    id: 1,
    slug: 'unpaid-wages',
    icon: '💰',
    enName: 'Unpaid Wages',
    hiName: 'अवैतनिक मजदूरी',
    bnName: 'অপ্রদত্ত মজুরি',
    teName: 'చెల్లని వేతనం',
    mrName: 'अवैतनिक मजूरी',
    taName: 'வழங்கப்படாத கூலி',
  },
  {
    id: 2,
    slug: 'workplace-safety',
    icon: '🦺',
    enName: 'Workplace Safety',
    hiName: 'कार्यस्थल सुरक्षा',
    bnName: 'কর্মক্ষেত্রের নিরাপত্তা',
    teName: 'కార్యస్థల భద్రత',
    mrName: 'कार्यस्थल सुरक्षा',
    taName: 'பணிமிடம் பாதுகாப்பு',
  },
  {
    id: 3,
    slug: 'unfair-firing',
    icon: '⛓️',
    enName: 'Unfair Firing',
    hiName: 'अन्यायपूर्ण निकाला जाना',
    bnName: 'অন্যায্য বরখাস্তকরণ',
    teName: 'అన్యాయమైన తొలగింపు',
    mrName: 'अन्यायकारक बर्खास्तगी',
    taName: 'நியாயமற்ற பணிநீக்கம்',
  },
  {
    id: 4,
    slug: 'contract-issues',
    icon: '📄',
    enName: 'Contract Issues',
    hiName: 'अनुबंध समस्याएं',
    bnName: 'চুক্তির সমস্যা',
    teName: 'ఒప్పందం సమస్యలు',
    mrName: 'करार समस्या',
    taName: 'ஒப்பந்த சிக்கல்கள்',
  },
  {
    id: 5,
    slug: 'maternity-rights',
    icon: '👶',
    enName: 'Maternity Rights',
    hiName: 'मातृत्व अधिकार',
    bnName: 'মাতৃত্ব অধিকার',
    teName: 'ప్రసూతి హక్కులు',
    mrName: 'प्रसूती हक्क',
    taName: 'தாய்மை உரிமைகள்',
  },
  {
    id: 6,
    slug: 'child-labour',
    icon: '🛡️',
    enName: 'Child Labour',
    hiName: 'बाल श्रम',
    bnName: 'শিশু শ্রম',
    teName: 'బాల కార్మికత్వం',
    mrName: 'बाल मजूरी',
    taName: 'குழந்தை தொழிலாளர்',
  },
  {
    id: 7,
    slug: 'know-your-rights',
    icon: '📚',
    enName: 'Know Your Rights',
    hiName: 'अपने अधिकार को जानें',
    bnName: 'আপনার অধিকার জানুন',
    teName: 'మీ హక్కులను తెలుసుకోండి',
    mrName: 'आपल्या हक्कांना जाणून घ्या',
    taName: 'உங்கள் உரிமைகளை அறிந்து கொள்ளுங்கள்',
  },
  {
    id: 8,
    slug: 'emergency-helplines',
    icon: '☎️',
    enName: 'Emergency Helplines',
    hiName: 'आपातकालीन हेल्पलाइन',
    bnName: 'জরুরি হেল্পলাইন',
    teName: 'ఎమర్జెన్సీ హెల్ప్‌లైన్‌లు',
    mrName: 'आपातकालीन हेल्पलाइन',
    taName: 'அவசர உதவி வரிகள்',
  },
  {
    id: 9,
    slug: 'rural-issues',
    icon: '🌾',
    enName: 'Rural Issues',
    hiName: 'ग्रामीण समस्याएं',
    bnName: 'গ্রামীণ সমস্যা',
    teName: 'గ్రామీణ సమస్యలు',
    mrName: 'ग्रामीण समस्या',
    taName: 'கிராமப்புற சிக்கல்கள்',
  },
]

export const indianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
]

export const labourOffices = {
  'Andhra Pradesh': {
    address: 'Labour Department, Hyderabad',
    phone: '040-23123456',
    lat: 17.3850,
    lng: 78.4867,
  },
  'Maharashtra': {
    address: 'Labour Department, Mumbai',
    phone: '022-12345678',
    lat: 19.0760,
    lng: 72.8777,
  },
  'Tamil Nadu': {
    address: 'Labour Department, Chennai',
    phone: '044-24312890',
    lat: 13.0827,
    lng: 80.2707,
  },
  'Karnataka': {
    address: 'Labour Department, Bengaluru',
    phone: '080-23456789',
    lat: 12.9716,
    lng: 77.5946,
  },
  'Delhi': {
    address: 'Labour Department, New Delhi',
    phone: '011-23456789',
    lat: 28.6139,
    lng: 77.2090,
  },
  'Uttar Pradesh': {
    address: 'Labour Department, Lucknow',
    phone: '0522-2234567',
    lat: 26.8467,
    lng: 80.9462,
  },
  'West Bengal': {
    address: 'Labour Department, Kolkata',
    phone: '033-2290891',
    lat: 22.5726,
    lng: 88.3639,
  },
  'Gujarat': {
    address: 'Labour Department, Gandhinagar',
    phone: '079-23212345',
    lat: 23.2156,
    lng: 72.6369,
  },
  'Punjab': {
    address: 'Labour Department, Chandigarh',
    phone: '0172-2748901',
    lat: 30.7333,
    lng: 76.7794,
  },
  'Rajasthan': {
    address: 'Labour Department, Jaipur',
    phone: '0141-2234567',
    lat: 26.9124,
    lng: 75.7873,
  },
}
